<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CommandHandlers\" />
    <Folder Include="Commands\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroServices.Domain.Core\MicroServices.Domain.Core.csproj" />
  </ItemGroup>

</Project>
